apiVersion: v1
kind: Pod
metadata:
  name: ghostportlabel
  labels:
    run: randomlabel
spec:
  containers:
  - name: ghostportlabel
    image: ghost
    ports:
      - containerPort: 2368
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-service-randomlabel
  labels:
    run: randomlabel
spec:
  ports:
  - port: 2368
    protocol: TCP
  selector:
    run: randomlabel
