apiVersion: v1
kind: ConfigMap
metadata:
  name: my-nginx-v2
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            return 200 'Kubernetes is hot, time for a beer, v2!\n';
        }
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: my-nginx
  name: my-nginx
#  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: my-nginx
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - image: nginx:alpine
        name: my-nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d
      volumes:
       - name: config-volume
         configMap:
           name: my-nginx-v2
